//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDimension
    {
        public string AccountID { get; set; }
        public string AccountName { get; set; }
        public string DimensionID { get; set; }
        public string DimensionName { get; set; }
        public string DimensionTypeID { get; set; }
        public string DimensionTypeName { get; set; }
        public string DimensionAccountDesc { get; set; }
        public Nullable<byte> active { get; set; }
        public Nullable<System.DateTime> rowcreateddate { get; set; }
        public string MachineIP { get; set; }
        public string MachineName { get; set; }
        public string MachineUser { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> rowupdateddate { get; set; }
        public string Machineipupdated { get; set; }
        public string Machinenameupdated { get; set; }
        public string Machineuserupdated { get; set; }
        public Nullable<int> useridupdated { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Dimension Dimension { get; set; }
    }
}
