//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Account1 = new HashSet<Account>();
            this.AccountDimensions = new HashSet<AccountDimension>();
        }
    
        public string AccountID { get; set; }
        public byte AccountTypeID { get; set; }
        public string AccountName { get; set; }
        public string AccountDesc { get; set; }
        public Nullable<byte> Leaf { get; set; }
        public string ParentAccountID { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> rowcreateddate { get; set; }
        public string MachineIP { get; set; }
        public string MachineName { get; set; }
        public string MachineUser { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> rowupdateddate { get; set; }
        public string Machineipupdated { get; set; }
        public string Machinenameupdated { get; set; }
        public string Machineuserupdated { get; set; }
        public Nullable<int> useridupdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Account1 { get; set; }
        public virtual Account Account2 { get; set; }
        public virtual AccountType AccountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountDimension> AccountDimensions { get; set; }
    }
}
