//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyRate
    {
        public string CurrencyID { get; set; }
        public System.DateTime CurrRateDate { get; set; }
        public Nullable<decimal> CurrRate { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> rowcreateddate { get; set; }
        public string MachineIP { get; set; }
        public string MachineName { get; set; }
        public string MachineUser { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> rowupdateddate { get; set; }
        public string Machineipupdated { get; set; }
        public string Machinenameupdated { get; set; }
        public string Machineuserupdated { get; set; }
        public Nullable<int> useridupdated { get; set; }
    
        public virtual Currency Currency { get; set; }
    }
}
