//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunctionGroupMenu
    {
        public int FunctionGroupMenuID { get; set; }
        public Nullable<int> FunctionGroupID { get; set; }
        public Nullable<int> FunctionID { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> deactivateddate { get; set; }
        public Nullable<System.DateTime> rowcreateddate { get; set; }
    
        public virtual FunctionGroup FunctionGroup { get; set; }
        public virtual FunctionMenu FunctionMenu { get; set; }
    }
}
