//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GARD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GARD()
        {
            this.GARDDETAILS = new HashSet<GARDDETAIL>();
            this.GARDSTOCKs = new HashSet<GARDSTOCK>();
        }
    
        public long GARDNUM { get; set; }
        public string INVENTLOCATIONID { get; set; }
        public string CREATEUSER { get; set; }
        public System.DateTime GARDDATE { get; set; }
        public int LINECOUNT { get; set; }
        public Nullable<int> Gard_status { get; set; }
        public Nullable<System.DateTime> Gard_status_Date { get; set; }
        public string Gard_status_user { get; set; }
        public string MachineIp { get; set; }
        public string MachineName { get; set; }
        public string MachineUser { get; set; }
        public Nullable<int> userid { get; set; }
        public string MachineIPupdated { get; set; }
        public string MachineNameupdated { get; set; }
        public string MachineUserupdated { get; set; }
        public Nullable<int> useridupdated { get; set; }
        public Nullable<System.DateTime> rowcreateddate { get; set; }
        public Nullable<int> iabc { get; set; }
        public Nullable<int> idef { get; set; }
        public Nullable<int> ighi { get; set; }
        public Nullable<int> ijkl { get; set; }
        public string Sabc { get; set; }
        public string Sdef { get; set; }
        public string Sghi { get; set; }
        public string Sjkl { get; set; }
        public Nullable<System.DateTime> Dabc { get; set; }
        public Nullable<System.DateTime> Ddef { get; set; }
        public Nullable<System.DateTime> Dghi { get; set; }
        public Nullable<System.DateTime> Djkl { get; set; }
        public Nullable<decimal> DECabc { get; set; }
        public Nullable<decimal> DECdef { get; set; }
        public Nullable<decimal> DECghi { get; set; }
        public Nullable<decimal> DECjkl { get; set; }
    
        public virtual InventLocation InventLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GARDDETAIL> GARDDETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GARDSTOCK> GARDSTOCKs { get; set; }
    }
}
