//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GARDSTOCK
    {
        public long GARDNUM { get; set; }
        public string INVENTLOCATIONID { get; set; }
        public long stockid { get; set; }
        public string ITEMID { get; set; }
        public int QTY { get; set; }
        public string SERIAL { get; set; }
        public int UNITCODE { get; set; }
        public decimal WEIGHT { get; set; }
        public string MachineIP { get; set; }
        public string MachineUser { get; set; }
        public string MachineName { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> rowcreateddate { get; set; }
        public Nullable<int> iabc { get; set; }
        public Nullable<int> idef { get; set; }
        public Nullable<int> ighi { get; set; }
        public Nullable<int> ijkl { get; set; }
        public string Sabc { get; set; }
        public string Sdef { get; set; }
        public string Sghi { get; set; }
        public string Sjkl { get; set; }
        public Nullable<System.DateTime> Dabc { get; set; }
        public Nullable<System.DateTime> Ddef { get; set; }
        public Nullable<System.DateTime> Dghi { get; set; }
        public Nullable<System.DateTime> Djkl { get; set; }
        public Nullable<decimal> DECabc { get; set; }
        public Nullable<decimal> DECdef { get; set; }
        public Nullable<decimal> DECghi { get; set; }
        public Nullable<decimal> DECjkl { get; set; }
    
        public virtual GARD GARD { get; set; }
    }
}
