//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gold_SalesEntities : DbContext
    {
        public Gold_SalesEntities()
            : base("name=Gold_SalesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountDimension> AccountDimensions { get; set; }
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyEmp> CompanyEmps { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<CurrencyRate> CurrencyRates { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Dimension> Dimensions { get; set; }
        public virtual DbSet<DimensionType> DimensionTypes { get; set; }
        public virtual DbSet<FunctionGroup> FunctionGroups { get; set; }
        public virtual DbSet<FunctionGroupMenu> FunctionGroupMenus { get; set; }
        public virtual DbSet<FunctionMenu> FunctionMenus { get; set; }
        public virtual DbSet<GARD> GARDs { get; set; }
        public virtual DbSet<GARDDETAIL> GARDDETAILS { get; set; }
        public virtual DbSet<GARDSTOCK> GARDSTOCKs { get; set; }
        public virtual DbSet<InventLocation> InventLocations { get; set; }
        public virtual DbSet<InventSite> InventSites { get; set; }
        public virtual DbSet<INVENTTRANSFERLINE> INVENTTRANSFERLINEs { get; set; }
        public virtual DbSet<INVENTTRANSFERTABLE> INVENTTRANSFERTABLEs { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Invoice_Details> Invoice_Details { get; set; }
        public virtual DbSet<Invoice_error> Invoice_error { get; set; }
        public virtual DbSet<Invoice_Taxes> Invoice_Taxes { get; set; }
        public virtual DbSet<ItemGroup> ItemGroups { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemTax> ItemTaxes { get; set; }
        public virtual DbSet<ItemUnit> ItemUnits { get; set; }
        public virtual DbSet<pos_trans> pos_trans { get; set; }
        public virtual DbSet<pos_trans_grid> pos_trans_grid { get; set; }
        public virtual DbSet<purchline> purchlines { get; set; }
        public virtual DbSet<purchtable> purchtables { get; set; }
        public virtual DbSet<SalesRep> SalesReps { get; set; }
        public virtual DbSet<SalesRepComm> SalesRepComms { get; set; }
        public virtual DbSet<SalesRepTarget> SalesRepTargets { get; set; }
        public virtual DbSet<SecAudit> SecAudits { get; set; }
        public virtual DbSet<STOCK> STOCKs { get; set; }
        public virtual DbSet<StockDaily> StockDailies { get; set; }
        public virtual DbSet<sync> syncs { get; set; }
        public virtual DbSet<sync_details> sync_details { get; set; }
        public virtual DbSet<sync_taxes> sync_taxes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<sysversionaction> sysversionactions { get; set; }
        public virtual DbSet<sysversionaudit> sysversionaudits { get; set; }
        public virtual DbSet<sysversiondetail> sysversiondetails { get; set; }
        public virtual DbSet<sysversionLOG> sysversionLOGs { get; set; }
        public virtual DbSet<sysversion> sysversions { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<UserLocation> UserLocations { get; set; }
        public virtual DbSet<UserLocationFunction> UserLocationFunctions { get; set; }
        public virtual DbSet<UserLocFunGroup> UserLocFunGroups { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<vendor> vendors { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        public virtual DbSet<VoucherGrid> VoucherGrids { get; set; }
        public virtual DbSet<VoucherType> VoucherTypes { get; set; }
        public virtual DbSet<pos_trans_bk> pos_trans_bk { get; set; }
        public virtual DbSet<pos_trans_grid_bk> pos_trans_grid_bk { get; set; }
        public virtual DbSet<sync_info> sync_info { get; set; }
        public virtual DbSet<sync_info_toserver> sync_info_toserver { get; set; }
    }
}
