//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTTRANSFERLINE
    {
        public string TRANSFERID { get; set; }
        public decimal LINENUM { get; set; }
        public string ITEMGROUPID { get; set; }
        public string ITEMID { get; set; }
        public string SERIAL { get; set; }
        public decimal PRICE { get; set; }
        public decimal QTYSHIPPED { get; set; }
        public string UNIT_CODE { get; set; }
        public Nullable<long> STOCKID { get; set; }
        public Nullable<long> Newstockid { get; set; }
        public Nullable<long> Stockidnew { get; set; }
        public Nullable<System.DateTime> rowcreateddate { get; set; }
        public string MachineIP { get; set; }
        public string Machinename { get; set; }
        public string Machineuser { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> iabc { get; set; }
        public Nullable<int> idef { get; set; }
        public Nullable<int> ighi { get; set; }
        public Nullable<int> ijkl { get; set; }
        public string Sabc { get; set; }
        public string Sdef { get; set; }
        public string Sghi { get; set; }
        public string Sjkl { get; set; }
        public Nullable<System.DateTime> Dabc { get; set; }
        public Nullable<System.DateTime> Ddef { get; set; }
        public Nullable<System.DateTime> Dghi { get; set; }
        public Nullable<System.DateTime> Djkl { get; set; }
        public Nullable<decimal> DECabc { get; set; }
        public Nullable<decimal> DECdef { get; set; }
        public Nullable<decimal> DECghi { get; set; }
        public Nullable<decimal> DECjkl { get; set; }
    
        public virtual INVENTTRANSFERTABLE INVENTTRANSFERTABLE { get; set; }
    }
}
