//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice_Details()
        {
            this.Invoice_Taxes = new HashSet<Invoice_Taxes>();
        }
    
        public int InvID { get; set; }
        public string CompanyID { get; set; }
        public string BranchID { get; set; }
        public int linenum { get; set; }
        public string ItemID { get; set; }
        public string itemserial { get; set; }
        public Nullable<int> item_karat { get; set; }
        public string unit_code { get; set; }
        public Nullable<decimal> item_qty { get; set; }
        public Nullable<decimal> sale_price { get; set; }
        public Nullable<decimal> line_price { get; set; }
        public Nullable<decimal> disc_prc { get; set; }
        public Nullable<decimal> disc_value { get; set; }
        public Nullable<decimal> line_Amount_PreTax { get; set; }
        public Nullable<int> taxes_count { get; set; }
        public Nullable<decimal> taxes_totval { get; set; }
        public Nullable<decimal> LineAmount { get; set; }
        public string Portal_InvID { get; set; }
        public Nullable<int> Inv_status { get; set; }
        public Nullable<System.DateTime> rowcreateddate { get; set; }
        public string MachineIP { get; set; }
        public string MachineUser { get; set; }
        public string MachineName { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> iabc { get; set; }
        public Nullable<int> idef { get; set; }
        public Nullable<int> ighi { get; set; }
        public Nullable<int> ijkl { get; set; }
        public string Sabc { get; set; }
        public string Sdef { get; set; }
        public string Sghi { get; set; }
        public string Sjkl { get; set; }
        public Nullable<System.DateTime> Dabc { get; set; }
        public Nullable<System.DateTime> Ddef { get; set; }
        public Nullable<System.DateTime> Dghi { get; set; }
        public Nullable<System.DateTime> Djkl { get; set; }
        public Nullable<decimal> DECabc { get; set; }
        public Nullable<decimal> DECdef { get; set; }
        public Nullable<decimal> DECghi { get; set; }
        public Nullable<decimal> DECjkl { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Taxes> Invoice_Taxes { get; set; }
    }
}
