//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Invoice_Details = new HashSet<Invoice_Details>();
        }
    
        public int InvID { get; set; }
        public string CompanyID { get; set; }
        public string BranchID { get; set; }
        public System.DateTime Invdate { get; set; }
        public string InvType { get; set; }
        public string InvCurr { get; set; }
        public Nullable<decimal> Inv_CurrRate { get; set; }
        public Nullable<decimal> Inv_CurrAmount { get; set; }
        public Nullable<decimal> Inv_LocalAmount { get; set; }
        public Nullable<decimal> Inv_Qty { get; set; }
        public Nullable<int> Inv_Lines { get; set; }
        public string CustomerID { get; set; }
        public Nullable<int> returnorder { get; set; }
        public Nullable<System.DateTime> closure_date { get; set; }
        public string remarks { get; set; }
        public string Portal_InvID { get; set; }
        public string Portal_InvLink { get; set; }
        public Nullable<int> Portal_syncstatus { get; set; }
        public Nullable<System.DateTime> rowcreateddate { get; set; }
        public string MachineIP { get; set; }
        public string MachineUser { get; set; }
        public string Machinename { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> rowupdateddate { get; set; }
        public string MachineIPupdated { get; set; }
        public string MachineUserupdated { get; set; }
        public string MachineNameupdated { get; set; }
        public Nullable<int> useridupdated { get; set; }
        public Nullable<int> iabc { get; set; }
        public Nullable<int> idef { get; set; }
        public Nullable<int> ighi { get; set; }
        public Nullable<int> ijkl { get; set; }
        public string Sabc { get; set; }
        public string Sdef { get; set; }
        public string Sghi { get; set; }
        public string Sjkl { get; set; }
        public Nullable<System.DateTime> Dabc { get; set; }
        public Nullable<System.DateTime> Ddef { get; set; }
        public Nullable<System.DateTime> Dghi { get; set; }
        public Nullable<System.DateTime> Djkl { get; set; }
        public Nullable<decimal> DECabc { get; set; }
        public Nullable<decimal> DECdef { get; set; }
        public Nullable<decimal> DECghi { get; set; }
        public Nullable<decimal> DECjkl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Details> Invoice_Details { get; set; }
        public virtual Invoice_error Invoice_error { get; set; }
    }
}
