//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_trans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pos_trans()
        {
            this.pos_trans_grid = new HashSet<pos_trans_grid>();
        }
    
        public int trans_id { get; set; }
        public string store_code { get; set; }
        public Nullable<System.DateTime> trans_date { get; set; }
        public string client_code { get; set; }
        public Nullable<decimal> trans_total { get; set; }
        public string remarks { get; set; }
        public Nullable<decimal> trans_total_21 { get; set; }
        public Nullable<decimal> trans_toatl_18 { get; set; }
        public Nullable<int> canceled { get; set; }
        public Nullable<int> syncstatus { get; set; }
        public string inventsiteid { get; set; }
        public Nullable<int> axsync { get; set; }
        public Nullable<int> returnorder { get; set; }
        public Nullable<System.DateTime> closure_date { get; set; }
        public Nullable<System.DateTime> rowcreateddate { get; set; }
        public Nullable<decimal> total_weight { get; set; }
        public Nullable<int> total_line { get; set; }
        public string MachineIP { get; set; }
        public string MachineUser { get; set; }
        public string Machinename { get; set; }
        public Nullable<int> userid { get; set; }
        public string MachineIPupdated { get; set; }
        public string MachineUserupdated { get; set; }
        public string MachineNameupdated { get; set; }
        public Nullable<int> useridupdated { get; set; }
        public Nullable<int> iabc { get; set; }
        public Nullable<int> idef { get; set; }
        public Nullable<int> ighi { get; set; }
        public Nullable<int> ijkl { get; set; }
        public string Sabc { get; set; }
        public string Sdef { get; set; }
        public string Sghi { get; set; }
        public string Sjkl { get; set; }
        public Nullable<System.DateTime> Dabc { get; set; }
        public Nullable<System.DateTime> Ddef { get; set; }
        public Nullable<System.DateTime> Dghi { get; set; }
        public Nullable<System.DateTime> Djkl { get; set; }
        public Nullable<decimal> DECabc { get; set; }
        public Nullable<decimal> DECdef { get; set; }
        public Nullable<decimal> DECghi { get; set; }
        public Nullable<decimal> DECjkl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pos_trans_grid> pos_trans_grid { get; set; }
    }
}
