//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_trans_grid
    {
        public int trans_id { get; set; }
        public int linenum { get; set; }
        public string store_code { get; set; }
        public string itemname { get; set; }
        public string unit_code { get; set; }
        public Nullable<decimal> item_weight { get; set; }
        public Nullable<decimal> sale_price { get; set; }
        public Nullable<decimal> slae_cost { get; set; }
        public Nullable<System.DateTime> trans_date { get; set; }
        public Nullable<int> item_sold { get; set; }
        public Nullable<int> syncstatus { get; set; }
        public string inventdimid { get; set; }
        public string parmitemid { get; set; }
        public Nullable<long> stockid { get; set; }
        public string itemserial { get; set; }
        public Nullable<System.DateTime> rowcreateddate { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> taxrate { get; set; }
        public Nullable<decimal> taxrates { get; set; }
        public Nullable<decimal> taxes { get; set; }
        public string MachineIP { get; set; }
        public string MachineUser { get; set; }
        public string MachineName { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> iabc { get; set; }
        public Nullable<int> idef { get; set; }
        public Nullable<int> ighi { get; set; }
        public Nullable<int> ijkl { get; set; }
        public string Sabc { get; set; }
        public string Sdef { get; set; }
        public string Sghi { get; set; }
        public string Sjkl { get; set; }
        public Nullable<System.DateTime> Dabc { get; set; }
        public Nullable<System.DateTime> Ddef { get; set; }
        public Nullable<System.DateTime> Dghi { get; set; }
        public Nullable<System.DateTime> Djkl { get; set; }
        public Nullable<decimal> DECabc { get; set; }
        public Nullable<decimal> DECdef { get; set; }
        public Nullable<decimal> DECghi { get; set; }
        public Nullable<decimal> DECjkl { get; set; }
    
        public virtual pos_trans pos_trans { get; set; }
    }
}
