//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchtable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public purchtable()
        {
            this.purchlines = new HashSet<purchline>();
        }
    
        public long purchid { get; set; }
        public string purchidax { get; set; }
        public string purchidOracle { get; set; }
        public Nullable<System.DateTime> purchdateopen { get; set; }
        public Nullable<System.DateTime> purchdateclose { get; set; }
        public string inventlocationid { get; set; }
        public string inventlocationidto { get; set; }
        public string remarks { get; set; }
        public string vendorid { get; set; }
        public Nullable<int> purchstatus { get; set; }
        public Nullable<int> axsync { get; set; }
        public Nullable<int> linecount { get; set; }
        public Nullable<decimal> totalweight { get; set; }
        public Nullable<int> empcode { get; set; }
        public Nullable<int> returnoder { get; set; }
        public string MachineIP { get; set; }
        public string MachineUser { get; set; }
        public string Machinename { get; set; }
        public Nullable<int> userid { get; set; }
        public string MachineIPupdated { get; set; }
        public string MachineUserupdated { get; set; }
        public string MachineNameupdated { get; set; }
        public Nullable<int> useridupdated { get; set; }
        public Nullable<System.DateTime> rowcreateddate { get; set; }
        public Nullable<int> iabc { get; set; }
        public Nullable<int> idef { get; set; }
        public Nullable<int> ighi { get; set; }
        public Nullable<int> ijkl { get; set; }
        public string Sabc { get; set; }
        public string Sdef { get; set; }
        public string Sghi { get; set; }
        public string Sjkl { get; set; }
        public Nullable<System.DateTime> Dabc { get; set; }
        public Nullable<System.DateTime> Ddef { get; set; }
        public Nullable<System.DateTime> Dghi { get; set; }
        public Nullable<System.DateTime> Djkl { get; set; }
        public Nullable<decimal> DECabc { get; set; }
        public Nullable<decimal> DECdef { get; set; }
        public Nullable<decimal> DECghi { get; set; }
        public Nullable<decimal> DECjkl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchline> purchlines { get; set; }
    }
}
