//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecAudit
    {
        public long SecActionID { get; set; }
        public Nullable<System.DateTime> SecAction_Date { get; set; }
        public Nullable<byte> SecAction { get; set; }
        public Nullable<byte> IsAdmin { get; set; }
        public Nullable<int> UserLocationID { get; set; }
        public Nullable<int> FunctionGroupID { get; set; }
        public Nullable<int> FunctionID { get; set; }
        public Nullable<int> userid { get; set; }
        public string MachineIP { get; set; }
        public string MachineName { get; set; }
        public string MachineUser { get; set; }
        public Nullable<System.DateTime> rowcreateddate { get; set; }
    }
}
