//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK
    {
        public long STOCKID { get; set; }
        public string itemserial { get; set; }
        public Nullable<decimal> itemweight { get; set; }
        public string itemgroupid { get; set; }
        public Nullable<int> itemunitcode { get; set; }
        public string InventLocationID { get; set; }
        public string BranchID { get; set; }
        public string parmitemid { get; set; }
        public Nullable<int> Suspend { get; set; }
        public Nullable<int> lastsyncstatus { get; set; }
        public string lastInvLoc { get; set; }
        public Nullable<System.DateTime> lastdate { get; set; }
        public string INtransID { get; set; }
        public Nullable<System.DateTime> INdate { get; set; }
        public string OutTrans { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public Nullable<long> oldstockid { get; set; }
        public Nullable<long> stockidold { get; set; }
        public Nullable<int> reservetype { get; set; }
        public string reserveid { get; set; }
        public string MachineIP { get; set; }
        public string MachineName { get; set; }
        public string MachineUser { get; set; }
        public Nullable<int> userid { get; set; }
        public string Machineipupdated { get; set; }
        public string Machinenameupdated { get; set; }
        public string Machineuserupdated { get; set; }
        public Nullable<int> useridupdated { get; set; }
        public Nullable<System.DateTime> rowcreateddate { get; set; }
        public Nullable<int> iabc { get; set; }
        public Nullable<int> idef { get; set; }
        public Nullable<int> ighi { get; set; }
        public Nullable<int> ijkl { get; set; }
        public string Sabc { get; set; }
        public string Sdef { get; set; }
        public string Sghi { get; set; }
        public string Sjkl { get; set; }
        public Nullable<System.DateTime> Dabc { get; set; }
        public Nullable<System.DateTime> Ddef { get; set; }
        public Nullable<System.DateTime> Dghi { get; set; }
        public Nullable<System.DateTime> Djkl { get; set; }
        public Nullable<decimal> DECabc { get; set; }
        public Nullable<decimal> DECdef { get; set; }
        public Nullable<decimal> DECghi { get; set; }
        public Nullable<decimal> DECjkl { get; set; }
    
        public virtual InventLocation InventLocation { get; set; }
    }
}
