//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sync_taxes
    {
        public long syn_id { get; set; }
        public long sync_details_linenum { get; set; }
        public int sync_taxes_linenum { get; set; }
        public int InvID { get; set; }
        public string CompanyID { get; set; }
        public string BranchID { get; set; }
        public int linenum { get; set; }
        public int TaxID { get; set; }
        public Nullable<decimal> TaxVal { get; set; }
    }
}
