//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sync
    {
        public long syn_id { get; set; }
        public string CompanyID { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public Nullable<int> sync_status { get; set; }
        public string sync_ip { get; set; }
        public string sync_user { get; set; }
        public Nullable<decimal> TotalLocalAmount { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public Nullable<int> TotalLines { get; set; }
        public Nullable<int> Invcount { get; set; }
        public Nullable<int> InvAccepted { get; set; }
        public Nullable<int> InvRejected { get; set; }
    }
}
