//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int userid { get; set; }
        public System.DateTime logindate { get; set; }
        public Nullable<System.DateTime> logoutdate { get; set; }
        public Nullable<byte> active { get; set; }
        public string CompanyID { get; set; }
        public string MachineIP { get; set; }
        public string MachineName { get; set; }
        public string MachineUser { get; set; }
        public Nullable<System.DateTime> rowcreateddate { get; set; }
    
        public virtual user user { get; set; }
    }
}
