//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLocation
    {
        public int UserLocationID { get; set; }
        public int userid { get; set; }
        public string InventLocationID { get; set; }
        public Nullable<byte> priority_flg { get; set; }
        public Nullable<byte> transferfrom_flg { get; set; }
        public Nullable<byte> transferto_flg { get; set; }
        public Nullable<byte> accepttransfer_flg { get; set; }
        public Nullable<byte> sales_flg { get; set; }
        public Nullable<byte> returnsales_flg { get; set; }
        public Nullable<byte> purchase_flg { get; set; }
        public Nullable<byte> returnpurchase_flg { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<System.DateTime> deactivateddate { get; set; }
        public Nullable<System.DateTime> rowcreateddate { get; set; }
    
        public virtual InventLocation InventLocation { get; set; }
        public virtual user user { get; set; }
    }
}
