//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLocationFunction
    {
        public long UserLocationFunctionID { get; set; }
        public int UserLocationID { get; set; }
        public int FunctionID { get; set; }
        public string GroupAssignedBy { get; set; }
        public Nullable<byte> active { get; set; }
        public Nullable<System.DateTime> deactivateddate { get; set; }
        public Nullable<System.DateTime> rowcreateddate { get; set; }
    
        public virtual FunctionMenu FunctionMenu { get; set; }
        public virtual UserLocation UserLocation { get; set; }
    }
}
