//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.UserLocations = new HashSet<UserLocation>();
            this.UserLogins = new HashSet<UserLogin>();
        }
    
        public int userid { get; set; }
        public string username { get; set; }
        public string userpassword { get; set; }
        public string userdescription { get; set; }
        public Nullable<byte> sysadmin { get; set; }
        public Nullable<byte> active { get; set; }
        public Nullable<System.DateTime> deactivateddate { get; set; }
        public Nullable<System.DateTime> rowcreateddate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLocation> UserLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLogin> UserLogins { get; set; }
    }
}
