//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold_Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherGrid
    {
        public string VoucherID { get; set; }
        public int VoucherLinenum { get; set; }
        public string CurrencyID { get; set; }
        public Nullable<decimal> DEBIT { get; set; }
        public Nullable<decimal> CREDIT { get; set; }
        public Nullable<decimal> CurrRate { get; set; }
        public Nullable<decimal> DEBIT_LOCAL { get; set; }
        public Nullable<decimal> CREDIT_LOCAL { get; set; }
        public string voucherLineDesc { get; set; }
        public string AccountID { get; set; }
        public string COST_CENTER_NO { get; set; }
        public string DOCUMENT_NO { get; set; }
        public Nullable<System.DateTime> rowcreateddate { get; set; }
        public string MachineIP { get; set; }
        public string MachineName { get; set; }
        public string MachineUser { get; set; }
        public Nullable<int> userid { get; set; }
        public string Machineipupdated { get; set; }
        public string Machinenameupdated { get; set; }
        public string Machineuserupdated { get; set; }
        public Nullable<int> useridupdated { get; set; }
        public Nullable<int> iabc { get; set; }
        public Nullable<int> idef { get; set; }
        public Nullable<int> ighi { get; set; }
        public Nullable<int> ijkl { get; set; }
        public string Sabc { get; set; }
        public string Sdef { get; set; }
        public string Sghi { get; set; }
        public string Sjkl { get; set; }
        public Nullable<System.DateTime> Dabc { get; set; }
        public Nullable<System.DateTime> Ddef { get; set; }
        public Nullable<System.DateTime> Dghi { get; set; }
        public Nullable<System.DateTime> Djkl { get; set; }
        public Nullable<decimal> DECabc { get; set; }
        public Nullable<decimal> DECdef { get; set; }
        public Nullable<decimal> DECghi { get; set; }
        public Nullable<decimal> DECjkl { get; set; }
    
        public virtual Voucher Voucher { get; set; }
    }
}
